[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"
xargo = false

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"
xargo = false

[target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc:main"
xargo = false

[target.aarch64-pc-windows-msvc]
image = "ghcr.io/cross-rs/aarch64-pc-windows-msvc:main"
xargo = false

[build.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED", 
    "RUSTFLAGS",
    "PKG_CONFIG_ALLOW_CROSS",
    "FONTCONFIG_NO_PKG_CONFIG",
    "RUST_FONTCONFIG_DLOPEN",
    "FONTCONFIG_STATIC",
    "PKG_CONFIG_PATH"
] 