name: Deploy Nettest Server

on:
  push:
    branches: [ parser_update ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v2.0.0, latest)'
        required: true
        type: string
        default: 'latest'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
    - name: Generate deployment matrix
      id: generate
      run: |
        # Читаем конфигурацию хостов из переменной окружения
        echo "Loading hosts config..."
        HOSTS_CONF_ENV="${{ vars.HOSTS_LIST }}"
        
        # Создаем JSON массив для matrix
        MATRIX='['
        FIRST=true
        
        # Извлекаем IP адреса из текстовой конфигурации
        echo "Extracting IP addresses from config..."
        
        # Проверяем что переменная не пустая
        if [ -z "$HOSTS_CONF_ENV" ]; then
          echo "ERROR: HOSTS_LIST variable is empty"
          exit 1
        fi
        
        # Извлекаем IP адреса (строки начинающиеся с IP)
        IP_ADDRESSES=$(echo "$HOSTS_CONF_ENV" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | tr '\n' ' ' | sed 's/ $//')
        
        if [ -z "$IP_ADDRESSES" ]; then
          echo "ERROR: No IP addresses found in HOSTS_LIST"
          echo "HOSTS_LIST length: ${#HOSTS_CONF_ENV}"
          echo "First 100 chars: ${HOSTS_CONF_ENV:0:100}"
          exit 1
        fi
        
        for IP in $IP_ADDRESSES; do
          if [ "$FIRST" = true ]; then
            FIRST=false
          else
            MATRIX="$MATRIX,"
          fi
          
          MATRIX="$MATRIX{\"host\":\"$IP\"}"
        done
        
        MATRIX="$MATRIX]"
        
        echo "Generated matrix: $MATRIX"
        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
        

  deploy:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    
    steps:
    - name: Debug matrix
      run: |
        echo "=== DEBUG: Matrix in deploy job ==="
        echo "matrix.host: '${{ matrix.host }}'"
        echo "matrix context: ${{ toJSON(matrix) }}"
        echo "needs.generate-matrix.outputs.matrix: '${{ needs.generate-matrix.outputs.matrix }}'"
        
        # Дополнительная отладка
        echo "=== Additional Debug Info ==="
        echo "Matrix content: ${{ needs.generate-matrix.outputs.matrix }}"
        
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ matrix.host }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: false
        script: |
          # set -e
          echo "Deploying to server: ${{ matrix.host }}"
          
          # Используем введенную версию
          DEPLOY_VERSION="${{ github.event.inputs.version }}"
          echo "Deploying version: $DEPLOY_VERSION"
          
          echo "Configuration loaded successfully"
          
          # Создаем конфигурационный файл
          echo "Creating /etc/nettest.conf..."
          
          # Извлекаем конфигурацию для конкретного сервера из JSON
          echo "Creating /etc/nettest.conf for server ${{ matrix.host }}..."
          
          # Создаем конфиг файл с конфигурацией из текстового формата
          echo "Creating /etc/nettest.conf for server ${{ matrix.host }}..."
          
          # Извлекаем конфигурацию для конкретного IP
          echo "${{ vars.HOSTS_LIST }}" | awk -v ip="${{ matrix.host }}" '
          BEGIN { in_config = 0; }
          /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/ {
              if ($0 ~ "^" ip) {
                  in_config = 1;
                  next;
              } else {
                  in_config = 0;
              }
          }
          /^---$/ {
              in_config = 0;
              next;
          }
          in_config && /^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*=/ {
              gsub(/^[[:space:]]*/, "");
              print;
          }
          ' > /etc/nettest.conf
          
          # Заменяем $SECRET_TOKEN на реальное значение
          sed -i 's/\$SECRET_TOKEN/'"${{ secrets.SECRET_TOKEN }}"'/g' /etc/nettest.conf
          
          # Проверяем что конфиг создался
          if [ ! -s /etc/nettest.conf ]; then
            echo "ERROR: Failed to create config file from JSON"
            exit 1
          fi
          

          
          echo "Configuration file created successfully"
          echo "Content of /etc/nettest.conf:"
          cat /etc/nettest.conf
          
          # Загружаем TLS сертификаты
          echo "Uploading TLS certificates..."
          echo '${{ secrets.PROD_TLS_CERT }}' > /root/specure-cd.crt
          echo '${{ secrets.PROD_TLS_KEY }}' > /root/specure-cd.key
          chmod 600 /root/specure-cd.crt /root/specure-cd.key
          echo "TLS certificates uploaded and secured"
          
          # Продолжаем с деплоем...
          
          echo "Deploying Nettest Server..."
          
          # Определяем версию Debian и выбираем соответствующий релиз
          DEBIAN_VERSION=$(cat /etc/debian_version 2>/dev/null | cut -d. -f1 || echo "0")
          echo "Detected Debian version: $DEBIAN_VERSION"
          
          # Проверяем поддержку версии
          if [ "$DEBIAN_VERSION" -lt 11 ]; then
            echo "ERROR: Debian version $DEBIAN_VERSION is not supported. Minimum required version is 11."
            echo "Please upgrade to Debian 11 or higher."
            exit 1
          elif [ "$DEBIAN_VERSION" -eq 11 ]; then
            NETTEST_URL="https://github.com/specure/nettest/releases/download/$DEPLOY_VERSION/nettest-debian-11-x86_64.tar.gz"
          elif [ "$DEBIAN_VERSION" -ge 12 ]; then
            # Для версий 12 и выше используем Debian 12
            NETTEST_URL="https://github.com/specure/nettest/releases/download/$DEPLOY_VERSION/nettest-debian-12-x86_64.tar.gz"
          else
            echo "ERROR: Unable to determine Debian version or unsupported version: $DEBIAN_VERSION"
            exit 1
          fi
          
          echo "Using URL: $NETTEST_URL"
          
          # Проверяем доступность релиза
          echo "Checking if release $DEPLOY_VERSION is available..."
          echo "Testing URL: $NETTEST_URL"
          
          # Сначала проверяем через GitHub API
          echo "Checking release via GitHub API..."
          API_RESPONSE=$(curl -s "https://api.github.com/repos/specure/nettest/releases/tags/$DEPLOY_VERSION")
          if echo "$API_RESPONSE" | grep -q '"message": "Not Found"'; then
            echo "❌ Release $DEPLOY_VERSION not found via GitHub API"
          else
            echo "✅ Release $DEPLOY_VERSION found via GitHub API"
          fi
          
          # Затем проверяем прямой доступ к файлу
          echo "Checking direct file access..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$NETTEST_URL")
          echo "HTTP response code (no redirect): $HTTP_CODE"
          
          # Проверяем с редиректами
          HTTP_CODE_REDIRECT=$(curl -s -o /dev/null -w "%{http_code}" -L "$NETTEST_URL")
          echo "HTTP response code (with redirect): $HTTP_CODE_REDIRECT"
          
          # Используем код с редиректами для финальной проверки
          if [ "$HTTP_CODE_REDIRECT" -ge 200 ] && [ "$HTTP_CODE_REDIRECT" -lt 400 ]; then
            echo "✅ Release $DEPLOY_VERSION is available (HTTP $HTTP_CODE_REDIRECT)"
          else
            echo "⚠️  WARNING: Release $DEPLOY_VERSION may not be available at $NETTEST_URL"
            echo "HTTP response codes: $HTTP_CODE (no redirect), $HTTP_CODE_REDIRECT (with redirect)"
            echo "Continuing with deployment anyway..."
            
            # Дополнительная диагностика
            echo "Trying to get more details..."
            curl -v "$NETTEST_URL" 2>&1 | head -20
            echo "Proceeding with download attempt..."
          fi
          
          NEW_BUILD_DIR="/tmp/nettest-new"
          OLD_BUILD_DIR="/tmp/nettest-old"
          CURRENT_BUILD_DIR="/opt/nettest"
          
          echo "Creating directories..."
          mkdir -p $NEW_BUILD_DIR $OLD_BUILD_DIR
          cd $NEW_BUILD_DIR
          
          echo "Downloading build for Debian $DEBIAN_VERSION..."
          echo "Download URL: $NETTEST_URL"
          
          # Пробуем скачать с подробным выводом
          wget --timeout=30 --tries=3 "$NETTEST_URL" -O nettest.tar.gz
          DOWNLOAD_EXIT_CODE=$?
          
          if [ $DOWNLOAD_EXIT_CODE -eq 0 ] && [ -f nettest.tar.gz ]; then
            FILE_SIZE=$(stat -c%s nettest.tar.gz 2>/dev/null || echo 0)
            echo "Downloaded file size: $FILE_SIZE bytes"
            
            if [ $FILE_SIZE -gt 1048576 ]; then
              echo "✅ Download successful ($(($FILE_SIZE / 1024 / 1024))MB)"
            else
              echo "❌ Download failed - file too small ($FILE_SIZE bytes)"
              echo "File contents:"
              head -c 200 nettest.tar.gz
              exit 1
            fi
          else
            echo "❌ Download failed with exit code: $DOWNLOAD_EXIT_CODE"
            echo "URL: $NETTEST_URL"
            echo "Trying alternative download method..."
            
            # Пробуем curl как альтернативу
            curl -L --connect-timeout 30 --max-time 300 "$NETTEST_URL" -o nettest.tar.gz
            CURL_EXIT_CODE=$?
            
            if [ $CURL_EXIT_CODE -eq 0 ] && [ -f nettest.tar.gz ]; then
              FILE_SIZE=$(stat -c%s nettest.tar.gz 2>/dev/null || echo 0)
              if [ $FILE_SIZE -gt 1048576 ]; then
                echo "✅ Download successful via curl ($(($FILE_SIZE / 1024 / 1024))MB)"
              else
                echo "❌ Download failed - file too small ($FILE_SIZE bytes)"
                exit 1
              fi
            else
              echo "❌ Both wget and curl failed"
              echo "wget exit code: $DOWNLOAD_EXIT_CODE"
              echo "curl exit code: $CURL_EXIT_CODE"
              exit 1
            fi
          fi
          
          echo "Extracting build..."
          tar -tzf nettest.tar.gz > /dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Invalid archive"
            exit 1
          fi
          
          tar -xzf nettest.tar.gz
          
          if [ ! -f nettest ]; then
            echo "Extraction failed"
            exit 1
          fi
          
          chmod +x nettest
          echo "Build prepared successfully"
          
          echo "Stopping existing process on port 443..."
          # Используем lsof для определения процесса на порту 443
          NETTEST_PID=$(lsof -ti :443 2>/dev/null || echo "")
          
          echo "DEBUG: NETTEST_PID = '$NETTEST_PID'"
          
          if [ ! -z "$NETTEST_PID" ]; then
            echo "Found existing process on port 443 (PID: $NETTEST_PID), stopping..."
            echo "DEBUG: About to run kill -TERM"
            kill -TERM $NETTEST_PID >/dev/null 2>&1 || echo "kill TERM completed"
            echo "DEBUG: kill -TERM completed"
            sleep 3
            
            echo "DEBUG: Checking if process still exists on port 443"
            if lsof -ti :443 >/dev/null 2>&1; then
              echo "Process still running on port 443, force killing..."
              echo "DEBUG: About to run kill -KILL"
              kill -KILL $NETTEST_PID >/dev/null 2>&1 || echo "kill KILL completed"
              echo "DEBUG: kill -KILL completed"
              sleep 2
            fi
            
            echo "DEBUG: Final check if process exists on port 443"
            if lsof -ti :443 >/dev/null 2>&1; then
              echo "Failed to stop process on port 443"
              exit 1
            else
              echo "Process stopped successfully"
            fi
          else
            echo "No existing process found on port 443"
          fi
          
          echo "=== IMMEDIATE DEBUGGING ==="
          echo "Process stopping completed, continuing with deployment..."
          echo "Current directory: $(pwd 2>/dev/null || echo 'failed to get pwd')"
          echo "Current user: $(whoami 2>/dev/null || echo 'failed to get user')"
          echo "Current working directory contents:"
          ls -la 2>/dev/null || echo "Failed to list directory"
          echo "Checking if nettest binary exists: $(ls -la nettest 2>/dev/null || echo 'not found')"
          
          # Убеждаемся что мы в правильной директории
          if [ ! -f nettest ]; then
            echo "Error: nettest binary not found in current directory"
            echo "Directory contents: $(ls -la 2>/dev/null || echo 'failed to list')"
            exit 1
          fi
          
          echo "Nettest binary found, proceeding..."
          echo "=== END IMMEDIATE DEBUGGING ==="
          
          # Проверяем, что порт 443 свободен
          echo "Checking if port 443 is free..."
          if netstat -tuln 2>/dev/null | grep :443 >/dev/null 2>&1; then
            echo "Warning: Port 443 is still in use"
            sleep 2
          else
            echo "Port 443 is free"
          fi
          
          echo "Port check completed, proceeding with backup..."
          
          if [ -d "$CURRENT_BUILD_DIR" ]; then
            echo "Backing up old build..."
            mv $CURRENT_BUILD_DIR $OLD_BUILD_DIR
            echo "Backup completed"
          else
            echo "No existing build to backup"
          fi
          
          echo "Installing new build..."
          mkdir -p $CURRENT_BUILD_DIR
          cp nettest $CURRENT_BUILD_DIR/
          cd $CURRENT_BUILD_DIR
          echo "Build installation completed"
          
          echo "Starting server..."
          nohup ./nettest -s -log info> nettest.log 2>&1 &
          NEW_PID=$!
          
          echo "Waiting for server (PID: $NEW_PID)..."
          
          # Ждем для запуска
          for i in {1..10}; do
            if ps -p $NEW_PID >/dev/null 2>&1; then
              echo "Server started successfully"
              break
            fi
            sleep 1
          done
          
          if ps -p $NEW_PID >/dev/null 2>&1; then
            echo "New server running (PID: $NEW_PID)"
            
            sleep 3
            
            if netstat -tuln 2>/dev/null | grep :443 >/dev/null 2>&1; then
              echo "Port 443 listening"
            else
              echo "Port 443 not listening"
            fi
            
            if [ -d "$OLD_BUILD_DIR" ]; then
              echo "Removing old build..."
              rm -rf $OLD_BUILD_DIR
            fi
            
            rm -rf $NEW_BUILD_DIR
            
            echo "Deployment completed successfully!"
            
          else
            echo "Server failed to start"
            echo "Checking logs:"
            cat $CURRENT_BUILD_DIR/nettest.log 2>/dev/null || echo "No logs"
            
            echo "Removing failed build..."
            rm -rf $CURRENT_BUILD_DIR $NEW_BUILD_DIR
            
            if [ -d "$OLD_BUILD_DIR" ]; then
              echo "Restoring old build..."
              mv $OLD_BUILD_DIR $CURRENT_BUILD_DIR
              
              cd $CURRENT_BUILD_DIR
              nohup ./nettest -s > nettest.log 2>&1 &
              OLD_PID=$!
              
              sleep 3
              if ps -p $OLD_PID >/dev/null 2>&1; then
                echo "Old server restored (PID: $OLD_PID)"
              else
                echo "Failed to restore old server"
                exit 1
              fi
            else
              echo "No old build to restore"
              exit 1
            fi
          fi
          
          echo "Final status:"
          ps aux | grep "nettest -s" | grep -v grep 2>/dev/null || echo "No nettest processes"
          netstat -tuln | grep :443 2>/dev/null || echo "Port 443 not listening" 